---
output: 
  stevetemplates::syllabus:
    latex_engine: xelatex
    dev: cairo_pdf
geometry: margin=1in
title: "**POLI502: Methods of Political Analysis**"
author: |
        | Jieun Byeon
        |
date: |
      | Fall 2024 \small (Updated: `r format(Sys.time(), '%D')`)
fontfamily: mathpazo
fontsize: 10pt
header-includes:
   - \linespread{1.05}
   - \usepackage{float}
   - \floatplacement{figure}{H}
   - \usepackage{longtable}
   - \usepackage{array}
   - \usepackage{natbib}
   - \usepackage{xcolor}
   - \usepackage{fontawesome5}
   - \usepackage[bottom, hang,flushmargin]{footmisc}
   - \renewcommand{\footnotelayout}{\onehalfspacing}
   - \usepackage{url}
   - \newcommand{\bookitem}{\item[\faBook]}
   - \newcommand{\chapteritem}{\item[\faBookOpen]}
   - \newcommand{\paperitem}{\item[\faFilePdf]}
   - \newcommand{\discussitem}{\item[\faQuestionCircle]}
   - \newcommand{\linkitem}{\item[\faLink]}
   - \newcommand{\quizitem}{\item[\faLightbulb]}
   - \newcommand{\youtubeitem}{\item[\faYoutube]}
#bibliography: references.bib
#bibliography-style: apsr
editor_options: 
  markdown: 
    wrap: 80
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
knitr::opts_chunk$set(cache=F,
                      fig.path = 'figs/',
                      cache.path='cache/',
                      warning=F,
                      message=F)
options(scipen=999)
library(tidyverse)
library(stevemisc)
library(lubridate)
```

# Course Objectives

POLI502 provides an introduction to the theory and practice of quantitative data
analysis techniques targeted toward Political Science graduate students. The
purpose of the course is to (1) build a foundational understanding of statistics
and ordinary least-squares (OLS) models; (2) read, understand and evaluate
quantitative research; and (3) design and conduct data analysis using the R
programming language. This course is designed for students with no prior
experience in the R programming language, so students will be given a
comprehensive introduction to its use. By the end of the term, students will
know how to summarize distributions of variables, estimate relationships between
variables, and illustrate quantities of interest via statistical graphics.

# Required Materials

\definecolor{hightlightColor}{HTML}{FFFF66}

-   Paul M. Kellstedt and Guy D. Whitten. 2018. The Fundamentals of Political
    Science Research, 3rd ed. New York: Cambridge University Press (Hereafter
    \colorbox{hightlightColor}{\it Kellstedt and Whitten})
    
-   Sean Gailmard. 2014. Statistical Modeling and Inference for Social Science. New York: Cambridge University Press (Hereafter
    \colorbox{hightlightColor}{\it Gailmard})
    
-   Ismay, Chester and Albert Y. Kim. 2024. *Statistical Inference via Data
    Science: A ModernDive into R and the Tidyverse*, First Edition. Chapman and
    Hall. You can access it at <https://moderndive.com/> (Hereafter
    \colorbox{hightlightColor}{\it Moderndive}).


# Statistical Analysis Resources

Most the analysis examples and assignments in this course will employ R and
RStudio, both of which can be freely downloaded and installed (R:
<https://www.r-project.org/> RStudio:
<https://posit.co/download/rstudio-desktop/>).

Here are some useful guides to using R that will come in handy throughout the
semester:

-   [R for Non-Programmers: A Guide for Social
    Scientists](https://bookdown.org/daniel_dauber_io/r4np_book/)

-   [SimpleR - Using R for Introductory
    Statistics](https://cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf)


# Course Requirements

## Course Formats

1.  *Problem sets* (12 $\times$ 2.5% each = 30%, due by 11:59 PM on Friday of the assigned week)

After each class, students must complete the corresponding problem set and submit it through Blackboard. Submissions must include both (1) responses to the questions and/or interpretations of output and (2) the code necessary to complete each exercise in R.

2.  *Midterm/Final Exams* (2 $\times$ 25% each = 50%)

While using Google, YouTube, and Chat GPT is encouraged, you are required to
write and hand in your own computer code and final write-up of the answers. DO
NOT simply copy computer code or answers from your classmates.

3. *Quizzes* (10 $\times$ 2% each = 20%)

After each class, students must complete the corresponding quizzes. will feature theory-based questions to check whether students have thoroughly read the reading materials.

## Rubric

The following grading scale maps the final grade-points to letter grades. A:
90-100; B+: 87-89; B: 80-86; C+: 77-79; C:70-76; D+: 67-69; D: 60-66; F: 0-59.
Standard rounding rules apply. Late work will lose ten points for every six
hours that it is turned in late. Further, tests may be curved, but this is at
the discretion of the instructor.

## Technology Requirements

You will access most of your course material and submit assignments through
Blackboard. Please familiarize yourself with Blackboard during the first week of
classes. You will need access to a working computer with internet access for the
course. If your computer fails, please use one in the campus computer labs or
borrow a laptop from the library.

Assignments must be submitted as described on the assignment and through
Blackboard. Blackboard requires documents to be submitted in `PDF` format.
Otherwise, I cannot read your submission.

Please be sure your browser is updated and compatible with Blackboard. Google
Chrome is the recommended browser for Blackboard. The university provides
students with Microsoft Office 365 free of charge. This allows you to install
Word, Excel, PowerPoint, Outlook, OneNote, Publisher, and Access on up to 5 PCs
or Macs and Office apps on other mobile devices including tablets. Office 365
also includes unlimited cloud storage on OneDrive. For more information about
university software, please visit the Software section of
\texttt{\href{my.sc.edu}{my.sc.edu}}.

If you have problems or questions about computer technology or Blackboard,
please contact the Division of Information Technology's (DoIT's) Service Desk at
(803) 777-1800 or submit an online request through the Self-Service Portal or
visit Carolina Tech Zone. The Service Desk is open Monday--Friday from 8:00
AM--6:00 PM (Eastern Daylight Time). If you contact DoIT with a technology
problem, make sure you save your documents with the case number.

## Accommodations

If you are a person with a disability and anticipate needing any type of
accommodation in order to participate in this class, please advise me and make
appropriate arrangements with the Student Disability Resource Center. All
disability accommodations must be approved through the Office of Student
Disability Services. For more information, see
\texttt{\href{https://sc.edu/about/offices_and_divisions/student_disability_resource_center/}{Student Disability Resource Center}}.
Special accommodations are also available for veterans on duty and for parents.

### Medical Matters

Reasonable accommodations are available for students with a documented
disability. If you have a disability and may need accommodations to fully
participate in this class, contact the Office of Student Disability Services:
777-6142, TDD 777-6744, email
\texttt{\href{sasds@mailbox.sc.edu}{sasds@mailbox.sc.edu}}, or stop by Close
Hipp Room 112A.

## Academic Dishonesty Policy

I will enforce rigorous standards of academic integrity in all aspects of this
course. For the detailed policy of the University of South Carolina regarding
the definitions of acts considered to fall under academic dishonesty and
possible ensuing sanctions, see the University Honor Code:
\texttt{\href{http://www.sc.edu/policies/ppm/staf625.pdf}{Academic
Responsibility -- The Honor Code}}. Should you have any questions about possibly
improper research citations or references, or any activity that may be
interpreted as academic dishonesty, please see me before the assignment is due
to discuss the matter.

## Personal Integrity

I am committed to creating and fostering a positive learning and working
environment based on open communication, mutual respect, and inclusion. I will
not tolerate discrimination and harassment on the basis of identity or status,
including race, color, national origin, religion, sex, gender, age, disability,
sexual orientation, genetics, or veteran status. For more information on the
University Student Non-Discrimination and Non-Harassment Policy, see
\texttt{\href{https://www.sc.edu/about/offices_and_divisions/equal_opportunities_programs/documents/student_non-discrimination_and_non-harassment_policy.pdf}{Student Non-Discrimination and Non-Harassment Policy}}.
If you want to speak to someone about an incident involving harassment, sexual
assault, or interpersonal violence, you can call 803-777-8248 to talk to a
trained interpersonal violence advocate.

## Additional Information

Students are responsible for knowing both university and course schedules.
\newline The academic calendar is available at:
\texttt{\href{https://sc.edu/about/offices_and_divisions/registrar/academic_calendars/2024-25_calendar.php}{University Registrar}}.

\newpage

# Class Schedule

All course deadlines are listed in Eastern Time Zone. Blackboard will record all
deadlines in this time zone. If you are in a different time zone, then plan
accordingly. Each week will begin on a [insert day of week] and will end on
[insert day of week].

Students must complete the required readings before class sessions and are encouraged to attend lectures and check Blackboard for updates. The course schedule is listed below:

\vspace{0.3cm}

\faBook: book, \faFilePdf: journal article or manuscript, \faLink: hyperlink, \faYoutube: video, and \faLightbulb: weekly assignments.

## Week 1: Scientific Study of Political Science and Theory Building

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, Chapter 1, 2
  \linkitem {\it Moderndive}, Chapter 1 :
  \href{https://moderndive.com/1-getting-started.html}{https://moderndive.com/1-getting-started.html}
  \youtubeitem \href{https://www.youtube.com/watch?v=FIrsOBy5k58}{RStudio for the Total Beginner}
  \youtubeitem \href{https://www.youtube.com/watch?v=w5dOALbZ9HE}{R tutorial - How to Create and Name Vectors in R}
  \youtubeitem \href{https://www.youtube.com/watch?v=O7KL17QZNqg}{R tutorial - Learn How to Create and Name Matrices in R}
  \quizitem Problem Set 1 (due by 11:59 PM on Friday)
\end{itemize}
```

\vspace{0.3cm}

## Week 2: Causal Relationships and Research Design

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, Chapter 3, 4
  \linkitem {\it Moderndive}, Chapter 1 :
  \href{https://moderndive.com/1-getting-started.html}{https://moderndive.com/1-getting-started.html}
  \quizitem Problem Set 2 (due by 11:59 PM on Friday)
  \quizitem Quiz 1
\end{itemize}
```

\vspace{0.3cm}

## Week 3: Data and Information I: Measuring Concepts of Interest

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, Chapter 5
  \chapteritem Gailmard, pp.14-21
  \linkitem {\it Moderndive}, Chapter 3, 4 :
  \href{https://moderndive.com/3-wrangling.html}{https://moderndive.com/3-wrangling.html}
  \href{https://moderndive.com/4-tidy.html}{https://moderndive.com/4-tidy.html}
  \quizitem Problem Set 3 (due by 11:59 PM on Friday)
  \quizitem Quiz 2
\end{itemize}
```

\vspace{0.3cm}

## Week 4: Data and Information II: Univariate & Bivariate Distribution

```{=tex}
\begin{itemize}
  \chapteritem Gailmard, pp. 21-37
  \chapteritem Kellstedt and Whitten, Chapter 6
  \linkitem {\it Moderndive}, Chapter 2 :
  \href{https://moderndive.com/2-viz.html}{https://moderndive.com/2-viz.html}
  \quizitem Problem Set 4 (due by 11:59 PM on Friday)
  \quizitem Quiz 3
\end{itemize}
```

\vspace{0.3cm}

## Week 5: Probability and Statistical Inference I: Probability Theory

```{=tex}
\begin{itemize}
  \chapteritem Gailmard, pp.83-115
  \youtubeitem \href{https://www.youtube.com/watch?v=SrEmzdOT65s}{Basic probability: Joint, marginal and conditional probability | Independence}
  \quizitem Problem Set 5 (due by 11:59 PM on Friday)
  \quizitem Quiz 4
\end{itemize}
```

\vspace{0.3cm}

## Week 6: Probability and Statistical Inference II: Populations and Samples

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, pp.143-148
  \linkitem {\it Moderndive}, Chapter 7 :
  \href{https://moderndive.com/7-sampling.html}{https://moderndive.com/7-sampling.html}
  \youtubeitem \href{https://www.youtube.com/watch?v=7S7j75d3GM4}{Sampling Distributions}
  \quizitem Problem Set 6 (due by 11:59 PM on Friday)
  \quizitem Quiz 5
\end{itemize}
```

\vspace{0.3cm}

## Week 7: Probability and Statistical Inference III: Normal Distribution and Confidence Intervals

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, pp.148-160
  \chapteritem Gailmard, pp.160-168, 187-203
  \linkitem {\it Moderndive}, Chapter 8 :
  \href{https://moderndive.com/8-confidence-intervals.html}{https://moderndive.com/8-confidence-intervals.html}
  \quizitem Problem Set 7 (due by 11:59 PM on Friday)
  \quizitem \colorbox{hightlightColor}{Midterm}
\end{itemize}
```

\vspace{0.3cm}

## Week 8: Hypothesis Testing I

```{=tex}
\begin{itemize}
  \chapteritem Gailmard, pp.236-246
  \chapteritem Kellstedt and Whitten, pp.161-166
  \linkitem {\it Moderndive}, Chapter 9 :
  \href{https://moderndive.com/9-hypothesis-testing.html}{https://moderndive.com/9-hypothesis-testing.html}
  \quizitem Problem Set 8 (due by 11:59 PM on Friday)
  \quizitem Quiz 6
\end{itemize}
```

\vspace{0.3cm}

## Week 9: Hypothesis Testing II 

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, pp.166-188
  \quizitem Problem Set 9 (due by 11:59 PM on Friday)
  \quizitem Quiz 7
\end{itemize}
```

\vspace{0.3cm}

## Week 10: Bivariable Linear Regression I

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, pp.188-207
  \linkitem {\it Moderndive}, Chapter 5 :
  \href{https://moderndive.com/5-regression.html}{https://moderndive.com/5-regression.html}
  \quizitem Problem Set 10 (due by 11:59 PM on Friday)
  \quizitem Quiz 8
\end{itemize}
```

\vspace{0.3cm}

## Week11: Bivariable Linear Regression II

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, pp.207-215
  \linkitem {\it Moderndive}, Chapter 10.2 :
  \href{https://moderndive.com/10-inference-for-regression.html\#regression-interp}{https://moderndive.com/10-inference-for-regression.html\#regression-interp}
  \quizitem Problem Set 11 (due by 11:59 PM on Friday)
  \quizitem Quiz 9
\end{itemize}
```

## Week 12: Introduction to Multiple Regression I

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, Chapter 10
  \linkitem {\it Moderndive}, Chapter 6:
  \href{https://moderndive.com/6-multiple-regression.html}{https://moderndive.com/6-multiple-regression.html}
  \quizitem Quiz 10
\end{itemize}
```

\vspace{0.3cm}

## Week 13: Introduction to Multiple Regression II

```{=tex}
\begin{itemize}
  \chapteritem Kellstedt and Whitten, pp.246-258
  \linkitem {\it Moderndive}, Chapter 6:
    \href{https://moderndive.com/6-multiple-regression.html}{https://moderndive.com/6-multiple-regression.html}
  \quizitem Problem Set 12 (due by 11:59 PM on Friday)
\end{itemize}
```

\vspace{0.3cm}

## Week 14: Thanksgiving

\vspace{0.3cm}

## Week 15: Final Wrap-up

```{=tex}
\begin{itemize}
  \quizitem \colorbox{hightlightColor}{Final Exam}
\end{itemize}
```




