---
title: "**POLI706: Advanced Methods of Political Analysis**"
subtitle: |
          | 
          | Problem set 1
          |
documentclass: article
format: 
  pdf:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
    code-block-bg: light
    code-block-border-left: "#31BAE9"
    linkcolor: highlight
    urlcolor: highlight
    highlight-style: atom-one
#bibliography: W2.bib
header-includes:
  -  \usepackage{hyperref}
  -  \usepackage{mathpazo}
  -  \usepackage{bookmark}
  -  \definecolor{light}{HTML}{EEEEEE}
  -  \definecolor{highlight}{HTML}{9A2A2A}
  -  \definecolor{dark}{HTML}{330033}
  -  \usepackage{setspace}\singlespacing
  -  \usepackage{fvextra}
  -  \setmainfont[ItalicFont = {TeXGyrePagella-Italic}]{TeX Gyre Pagella}
  -  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  #-  \setmonofont{Fira Code}[Contextuals=Alternate]
  -  \makeatletter
  -  \renewcommand*\verbatim@nolig@list{}
  -  \makeatother
# You have to install fira font and tex gyre pagella
biblio-style: apsr
geometry: margin=1in
#fontfamily: mathpazo
fontsize: 11pt
link-citation: true
indent: true
---

```{r}
#| include: false
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, error = FALSE, 
                      message = FALSE, warning = FALSE)
# Load packages to import data
library(knitr);library(patchwork);library(tidyverse)
theme_set(theme_bw())
```


## Exercise 1

Recap your 502 experience. 

a. Find and load `data_assignment2.xlsx`.

\noindent `data_assignment2.xlsx` contains four variables: `country_name`, `year`, `v2x_polyarchy`, and `e_gdppc`. 

b. Define the *measurement level* of each variable in `data_assignment2.xlsx` for the following types of variables: continuous, ordinal, binary, categorical, and nominal.

## Exercise 2

Based on Exercise 1, perform both descriptive and causal inference. The goal is to understand the relationship between two variables and draw conclusions based on the data.

a. Make a scatter plot with `x = v2x_polyarchy` and `y = e_gdppc`. Label your axes and give the scatter plot a title.

b. Describe the pattern you observe in the scatter plot. Identify any trends, clusters, or outliers in the data. Based on the scatter plot, describe the relationship between electoral democracy index (`v2x_polyarchy`) and gross domestic production per capita (`e_gdppc`).

c. Hypothesize whether there is a causal relationship betweenelectoral democracy index and gross domestic production per capita.

d. Discuss whether the relationship observed could be interpreted as a causal one.

## Exercise 3

a. Make a scatter plot with `x = v2x_polyarchy > 17.5` and `y = v2x_polyarchy`.

b. Make a scatter plot with `x = v2x_polyarchy` and `y = v2x_polyarchy > 0.5`.

c. Draw linear fitted lines between `x` and `y` for `d` and `e`. Explain the differences between two plots based on the results of `a` in Exercise 2.

