---
title: "**POLI706: Advanced Methods of Political Analysis**"
subtitle: |
          | 
          | Problem set 11
          |
documentclass: article
format: 
  pdf:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
    code-block-bg: light
    code-block-border-left: "#31BAE9"
    linkcolor: highlight
    urlcolor: highlight
    highlight-style: atom-one
bibliography: ../references/references.bib
header-includes:
  -  \usepackage{hyperref}
  -  \usepackage{mathpazo}
  -  \usepackage{bookmark}
  -  \definecolor{light}{HTML}{EEEEEE}
  -  \definecolor{highlight}{HTML}{9A2A2A}
  -  \definecolor{dark}{HTML}{330033}
  -  \usepackage{setspace}\singlespacing
  -  \usepackage{fvextra}
  -  \setmainfont[ItalicFont = {TeXGyrePagella-Italic}]{TeX Gyre Pagella}
  -  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  #-  \setmonofont{Fira Code}[Contextuals=Alternate]
  -  \makeatletter
  -  \renewcommand*\verbatim@nolig@list{}
  -  \makeatother
# You have to install fira font and tex gyre pagella
biblio-style: apsr
geometry: margin=1in
#fontfamily: mathpazo
fontsize: 11pt
link-citation: true
indent: true
---

```{r}
#| include: false
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, error = FALSE, 
                      message = FALSE, warning = FALSE)
# Load packages to import data
library(ezpickr);library(knitr);library(patchwork);library(tidyverse)
```

For obvious reasons, as well as for non-obvious but actually more important reasons, you need to program all the steps yourself. You cannot use `{zelig}`, `{ggeffects}`, and `{marginaleffects}` .

## Exercise 1

Read @king2000 . Summarize what they are arguing, saying, and proposing. 

a. Explain their title. 

b. What is the difference between "predicted values" and "expected values"? 

c. What’s a "first difference"?

d. What are they saying about Bayesian approaches? 

e. Check the Google Scholar citation count for the article. 

The whole text should be written in pleasantly written prose without equations, etc. One page is the minimum.

## Exercise 2

"Make most of you statistical analysis" according to @king2000 ! For a dataset and model of great interest to you, produce two substantively different graph that mimics in style their Figure 1. That is, develop a single model of the form,

$$
y = \beta_0 + \beta_1x + \beta_2 z + \beta_3 xz + \beta_4 w + \beta_5 m + \beta_6 mw,
$$

which you then estimate. One graph should focus on what $x$ and $z$ do, the other on $m$ and $w$. Write up what the graph is telling you as if it were part of a paper. (**Hint!** Use parametric bootstrapping to make graphs.)

## References
